# codemagic.yaml — Fixed with App Store Connect API Key Reference and Dependencies
workflows:
  ios-testflight:
    name: iOS → TestFlight
    instance_type: mac_mini_m2
    max_build_duration: 90

    environment:
      vars:
        # REQUIRED FOR THE API BLOCK BELOW
        BUNDLE_ID: "com.strokesnchokes.strokesnchokes"
        ASC_KEY_ID: "FKNBK58HF2"  # ← Your 10-char Key ID
        APP_STORE_CONNECT_KEY_IDENTIFIER: "FKNBK58HF2"
        ASC_ISSUER_ID: "6c57ab02-4757-49f6-b5d2-462bcca62124"  # ← Your Issuer ID
        APP_STORE_CONNECT_ISSUER_ID: "6c57ab02-4757-49f6-b5d2-462bcca62124"
        # The key content should be stored as a SECRET in Codemagic UI.
        APP_STORE_PRIVATE_KEY: "API_KEY_CONTENT_SECRET"
        APP_STORE_CONNECT_PRIVATE_KEY: "API_KEY_CONTENT_SECRET"
        
      node: latest
      xcode: latest

    triggering:
      events:
        - push
        - tag
      branch_patterns:
        - pattern: main
          include: true

    scripts:
      - name: Install npm dependencies
        script: |
          npm ci --prefer-offline
          
      # --- NEW STEP: Install the missing Capacitor iOS package ---
      - name: Install Capacitor iOS dependency
        script: |
          npm install @capacitor/ios
      # ---------------------------------------------------------

      - name: Build web assets (Vite)
        script: |
          npm run build
          
      - name: Capacitor sync iOS
        script: |
          npx cap sync ios

      - name: Install CocoaPods and Verify Workspace
        script: |
          # 1. Install CocoaPods dependencies inside the iOS project folder
          cd ios/App
          pod install --repo-update
          
          # 2. Crucial diagnostic step: List contents of ios/App to confirm workspace existence
          echo "--- Listing contents of the ios/App directory (should show App.xcworkspace) ---"
          ls -R 
          
          # Return to root directory for subsequent steps
          cd ../..

      - name: Increment build number
        script: |
          cd ios/App
          agvtool new-version -all $(($(app-store-connect get-latest-testflight-build-number "$BUNDLE_ID") + 1))


      # --- NEW DIAGNOSTIC STEP ---
      - name: Verify Export Options Plist
        script: |
          EXPORT_PLIST_PATH="$CM_BUILD_DIR/ios/exportOptions.plist"
          
          echo "--- 1. Current working directory for context ---"
          pwd
          
          echo "--- 2. Checking for file existence and permissions ---"
          # This command will list the file or fail if it doesn't exist
          ls -l $EXPORT_PLIST_PATH 
          
          echo "--- 3. Printing file contents (excluding private key) ---"
          # This command will print the actual content Codemagic sees
          cat $EXPORT_PLIST_PATH 

          echo "--- Diagnostic complete. Proceeding to build... ---"
      # ---------------------------
      
      - name: Prepare and Build IPA for TestFlight
        script: |
        
          # Define the correct paths
          WORKSPACE_PATH="ios/App/App.xcworkspace"
          ARCHIVE_PATH="build/strokesnchokes.xcarchive"
          EXPORT_PLIST_PATH="$CM_BUILD_DIR/ios/exportOptions.plist"
          
          echo "Using workspace path: $WORKSPACE_PATH"

          # 1. Increment the build number
          (
            cd ios/App
            agvtool new-version -all $(($(app-store-connect get-latest-testflight-build-number "$BUNDLE_ID") + 1))
          )
          
          # 2. ARCHIVE using xcodebuild
          echo "--- Starting xcodebuild archive ---"
          xcodebuild archive \
            -workspace "$WORKSPACE_PATH" \
            -scheme "$IOS_SCHEME" \
            -configuration Release \
            -destination generic/platform=iOS \
            -archivePath "$ARCHIVE_PATH" | xcpretty

          # 3. EXPORT IPA using xcodebuild
          echo "--- Starting xcodebuild export ---"
          xcodebuild -exportArchive \
            -archivePath "$ARCHIVE_PATH" \
            -exportOptionsPlist "$EXPORT_PLIST_PATH" \
            -exportPath "build/ios/ipa" | xcpretty

    artifacts:
      - build/ios/ipa/*.ipa

    publishing:
      app_store_connect:
        # Authentication fields for App Store Connect
        key_id: $ASC_KEY_ID
        issuer_id: $ASC_ISSUER_ID
        api_key: $APP_STORE_PRIVATE_KEY 
        submit_to_testflight: true
        submit_to_app_store: false