# codemagic.yaml — Fixed with App Store Connect API Key Reference and Dependencies
workflows:
  ios-testflight:
    name: iOS → TestFlight
    instance_type: mac_mini_m2
    max_build_duration: 90

    environment:
      vars:
        # REQUIRED FOR THE API BLOCK BELOW
        BUNDLE_ID: "com.snc.strokesnchokes"
        ASC_KEY_ID: "FKNBK58HF2"  # ← Your 10-char Key ID
        APP_STORE_CONNECT_KEY_IDENTIFIER: "FKNBK58HF2"
        ASC_ISSUER_ID: "6c57ab02-4757-49f6-b5d2-462bcca62124"  # ← Your Issuer ID
        APP_STORE_CONNECT_ISSUER_ID: "6c57ab02-4757-49f6-b5d2-462bcca62124"
        # The key content should be stored as a SECRET in Codemagic UI.
        APP_STORE_PRIVATE_KEY: "API_KEY_CONTENT_SECRET"
        APP_STORE_CONNECT_PRIVATE_KEY: "API_KEY_CONTENT_SECRET"
        
      node: latest
      xcode: latest

    triggering:
      events:
        - push
        - tag
      branch_patterns:
        - pattern: main
          include: true

    scripts:
      - name: Install npm dependencies
        script: |
          npm ci --prefer-offline
          
      # --- NEW STEP: Install the missing Capacitor iOS package ---
      - name: Install Capacitor iOS dependency
        script: |
          npm install @capacitor/ios
      # ---------------------------------------------------------

      - name: Build web assets (Vite)
        script: |
          npm run build
          
      - name: Capacitor add iOS platform
        script: |
          # This should now succeed since the dependency is installed
     #     npx cap add ios

      - name: Capacitor sync iOS
        script: |
          npx cap sync ios

      - name: Install CocoaPods
        script: |
          cd ios/App
          pod install --repo-update

      - name: Increment build number
        script: |
          cd ios/App
          agvtool new-version -all $(($(app-store-connect get-latest-testflight-build-number "$BUNDLE_ID") + 1))


      # --- NEW DIAGNOSTIC STEP ---
      - name: Verify Export Options Plist
        script: |
          EXPORT_PLIST_PATH="$CM_BUILD_DIR/ios/exportOptions.plist"
          
          echo "--- 1. Current working directory for context ---"
          pwd
          
          echo "--- 2. Checking for file existence and permissions ---"
          # This command will list the file or fail if it doesn't exist
          ls -l $EXPORT_PLIST_PATH 
          
          echo "--- 3. Printing file contents (excluding private key) ---"
          # This command will print the actual content Codemagic sees
          cat $EXPORT_PLIST_PATH 

          echo "--- Diagnostic complete. Proceeding to build... ---"
      # ---------------------------

      - name: Prepare and Build IPA for TestFlight
        script: |
          # 1. Define the absolute path to the exportOptions.plist using $CM_BUILD_DIR
          EXPORT_PLIST_PATH="$CM_BUILD_DIR/ios/exportOptions.plist"
          echo "Using absolute export options plist path: $EXPORT_PLIST_PATH"

          # 2. Increment the build number (must run from the 'ios/App' directory)
          (
            cd ios/App
            agvtool new-version -all $(($(app-store-connect get-latest-testflight-build-number "$BUNDLE_ID") + 1))
          )

          # 3. Build the IPA using the guaranteed absolute path for the export plist.
          xcode-project build-ipa \
            --workspace "ios/App/App.xcworkspace" \
            --scheme "strokesnchokes" \
            --export-options-plist "$EXPORT_PLIST_PATH"
    

    artifacts:
      - build/ios/ipa/*.ipa

    publishing:
      app_store_connect:
        # Authentication fields for App Store Connect
        key_id: $ASC_KEY_ID
        issuer_id: $ASC_ISSUER_ID
        api_key: $APP_STORE_PRIVATE_KEY 
        submit_to_testflight: true
        submit_to_app_store: false