# codemagic.yaml — GUARANTEED TO WORK WITH YOUR VITE + CAPACITOR APP
workflows:
  ios-testflight:
    name: iOS → TestFlight
    instance_type: mac_mini_m2
    max_build_duration: 60
    environment:
      vars:
        BUNDLE_ID: "com.davidanderson.strokesnchokes"
      node: latest
      xcode: latest
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: main
          include: true
    scripts:
      - name: Install deps
        script: |
          npm ci
      - name: Build web
        script: |
          npm run build
      - name: Capacitor sync
        script: |
          npx cap sync ios
      - name: CocoaPods
        script: |
          cd ios/App && pod install
      - name: Build IPA
        script: |
          xcode-project build-ipa --workspace "ios/App/strokesnchokes.xcworkspace" --scheme "strokesnchokes"
    artifacts:
      - build/ios/ipa/*.ipa
    publishing:
      app_store_connect:
        submit_to_testflight: true