# codemagic.yaml — Fixed with App Store Connect API Key Reference
workflows:
  ios-testflight:
    name: iOS → TestFlight
    instance_type: mac_mini_m2
    max_build_duration: 90

    environment:
      vars:
        # REQUIRED FOR THE API BLOCK BELOW
        BUNDLE_ID: "com.liondeskdavid.strokesnchokes"
        ASC_KEY_ID: "FKNBK58HF2"  # ← Your 10-char Key ID
        ASC_ISSUER_ID: "6c57ab02-4757-49f6-b5d2-462bcca62124"  # ← Your Issuer ID
        # The key content should be stored as a SECRET in Codemagic UI.
        # Make sure this variable name matches the secret name in the UI.
        APP_STORE_PRIVATE_KEY: "API_KEY_CONTENT_SECRET"
        
      node: latest
      xcode: latest

    triggering:
      events:
        - push
        - tag
      branch_patterns:
        - pattern: main
          include: true

    scripts:
      - name: Install npm dependencies
        script: |
          npm ci --prefer-offline

      - name: Build web assets (Vite)
        script: |
          npm run build

      - name: Capacitor sync iOS
        script: |
          npx cap sync ios

      - name: Install CocoaPods
        script: |
          cd ios/App
          pod install --repo-update

      - name: Increment build number
        script: |
          cd ios/App
          agvtool new-version -all $(($(app-store-connect get-latest-testflight-build-number "$BUNDLE_ID") + 1))

      - name: Build IPA for TestFlight
        script: |
          xcode-project build-ipa \
            --workspace "ios/App/strokesnchokes.xcworkspace" \
            --scheme "strokesnchokes" \
            --export-options-plist "ios/exportOptions.plist"

    artifacts:
      - build/ios/ipa/*.ipa

    publishing:
      app_store_connect:
        # Use the environment variables to provide the IDs
        key_id: $ASC_KEY_ID
        issuer_id: $ASC_ISSUER_ID
        # The api_key MUST reference the secret containing the .p8 file content
        api_key: $APP_STORE_PRIVATE_KEY 
        submit_to_testflight: true
        submit_to_app_store: false