# codemagic.yaml — Fixed workspace path and switched to xcodebuild for reliability.
workflows:
  ios-testflight:
    name: iOS → TestFlight
    instance_type: mac_mini_m2
    max_build_duration: 90

    environment:
      vars:
        # REQUIRED FOR THE API BLOCK BELOW
        BUNDLE_ID: "com.liondeskdavid.strokesnchokes"
        # The scheme name should match the name of the project/target in Xcode.
        IOS_SCHEME: "strokesnchokes" 
        ASC_KEY_ID: "FKNBK58HF2"  # ← Your 10-char Key ID
        ASC_ISSUER_ID: "6c57ab02-4757-49f6-b5d2-462bcca62124"  # ← Your Issuer ID
        # The key content should be stored as a SECRET in Codemagic UI.
        APP_STORE_PRIVATE_KEY: "API_KEY_CONTENT_SECRET"
        
      node: latest
      xcode: latest

    triggering:
      events:
        - push
        - tag
      branch_patterns:
        - pattern: main
          include: true

    scripts:
      - name: Install npm dependencies
        script: |
          npm ci --prefer-offline
          
      - name: Install Capacitor iOS dependency
        script: |
          npm install @capacitor/ios

      - name: Build web assets (Vite)
        script: |
          npm run build
          
      - name: Capacitor add iOS platform
        script: |
          npx cap add ios

      - name: Capacitor sync iOS
        script: |
          npx cap sync ios

      - name: Install CocoaPods
        script: |
          cd ios/App
          pod install --repo-update

      - name: Prepare and Build IPA for TestFlight
        script: |
          # Define the correct paths
          WORKSPACE_PATH="ios/App/App.xcworkspace" # <-- CORRECTED PATH
          ARCHIVE_PATH="build/strokesnchokes.xcarchive"
          EXPORT_PLIST_PATH="$CM_BUILD_DIR/ios/exportOptions.plist"
          
          echo "Using workspace path: $WORKSPACE_PATH"
          echo "Using export options plist path: $EXPORT_PLIST_PATH"

          # 1. Increment the build number (must run from the 'ios/App' directory)
          (
            cd ios/App
            agvtool new-version -all $(($(app-store-connect get-latest-testflight-build-number "$BUNDLE_ID") + 1))
          )
          
          # 2. ARCHIVE using xcodebuild
          # This creates the .xcarchive file
          echo "--- Starting xcodebuild archive ---"
          xcodebuild archive \
            -workspace "$WORKSPACE_PATH" \
            -scheme "$IOS_SCHEME" \
            -configuration Release \
            -destination generic/platform=iOS \
            -archivePath "$ARCHIVE_PATH" | xcpretty

          # 3. EXPORT IPA using xcodebuild
          # This exports the IPA from the archive using the plist.
          echo "--- Starting xcodebuild export ---"
          xcodebuild -exportArchive \
            -archivePath "$ARCHIVE_PATH" \
            -exportOptionsPlist "$EXPORT_PLIST_PATH" \
            -exportPath "build/ios/ipa" | xcpretty

    artifacts:
      - build/ios/ipa/*.ipa

    publishing:
      app_store_connect:
        key_id: $ASC_KEY_ID
        issuer_id: $ASC_ISSUER_ID
        api_key: $APP_STORE_PRIVATE_KEY 
        submit_to_testflight: true
        submit_to_app_store: false